### ISSUE TITLE
Drag and Drop functionality

### ISSUE THREAD

**Issue by superfunkminister** [benkaiser/node-music-player#48] opened 2015-05-28 12:11 UTC
Allow the user to drag songs onto playlists and queue etc...

**Comment by benkaiser** [comment] 2015-05-28 12:31
Yeah this would be handy. I don't have a lot of time free atm but I'm open to pull requests!

**Comment by benkaiser** [comment] 2015-11-09 12:32
Closing this on github as it's not a bug.
Feature has been added to the trello board: https://trello.com/c/R07FJX6f/56-drag-and-drop-songs-onto-playlists-queue

**Closed by benkaiser** 2015-11-09 12:32 UTC
Labels: enhancement
