### ISSUE TITLE
Feature request: Allow an option to control the host player

### ISSUE THREAD

**Issue by myoblastic** [benkaiser/node-music-player#69] opened 2015-11-08 06:59 UTC
I want to use this as a music bot for voip through discord, so instead of serving the music to the person's computer, could it be adjusted so the music would be played through the server it is hosted on? Like the webpage with controls and such is still served to clients, but it controls the host server? I'm a total noob to node, so I don't know how much of a change or effort this would be.

**Comment by benkaiser** [comment] 2015-11-08 07:30
Hi @myoblastic ! Thanks for chiming in. I have had thoughts on this idea. However this is how I would like to solve it:

- Music is still always served to clients
- when a client gives itself a remote name (through the remote setup dialog), others can control it

Currently the capacity of this is only to let the others control it through commands such as:

```
http://localhost:2000/command/my_remote_name/playpause
http://localhost:2000/command/my_remote_name/prev
http://localhost:2000/command/my_remote_name/next
```
(see README for how I setup keyboard shortcuts for this).

What I would like added, is a way to turn a current player into a controlling mode, where it looks exactly the same, but every click / command is delivered to the player it is controlling. This wouldn't be too complex, what would need changing is all the functions in the `static/js/player/player.js` would need to be changed to (when in controlling mode) push the command through to the remote player.

This would solve your requirements (I hope) if you just ran the player on the server (would need chrome or firefox installed), then you can opt in the other clients to remote control it. 

It's not high on my list of priorities to implement currently, but you are welcome to have a go at it and submit a PR if you want. I'm also happy to give you advice on implementation if you need it!

**Comment by benkaiser** [comment] 2015-11-09 12:33
Also, this feature suggestion is already present on trello: https://trello.com/c/scqlw6yx/1-remote-control-support
I'm closing this as it's not a bug / current focus of development.

**Closed by benkaiser** 2015-11-09 12:33 UTC
